### ISSUE TITLE
Injected CSS rule broken for sites with incompatible `:has()` selector

### ISSUE THREAD

**Issue by nityy** [xarantolus/bromite-userscripts#1]
First of all, thanks for filtrite and these userscripts.

There are some sites with `:has()` selector e.g `ndtv.com` has selectors `.tbl-feed-card:has(.trc-content-sponsored)` and `.tbl-wrp:has(.i-amphtml-fill-content)`. Even if one such selector is present, whole rule does not apply, thus breaking the functionality of this userscript. Probably because this is incompatible with most of the browsers including Chrome on Android (See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility) and [caniuse](https://caniuse.com/css-has) on this).

I tested this on the domain above, removing these two selectors makes the ad whitespaces disappear. There are only 184 such selectors in whole user.js.

**Comment by xarantolus** [comment]
Nice catch, thank you for the very detailed report :)
