### ISSUE TITLE
Userscript

### ISSUE THREAD

**Issue by djsaikrishna** [xarantolus/bromite-userscripts#11]
I saw many scripts in greasyfork website but unfortunately those are not working with bromite and cromite, please help me. How to use those scripts in bromite or cromite. 

Thank you.

**Comment by xarantolus** [comment]
> many scripts in greasyfork website but unfortunately those are not working with bromite and cromite

You could ask the authors of those scripts.

> How to use those scripts in bromite or cromite

I have no idea, and it might be different for every script. You could install those scripts and see how they fail in the dev tools by [connecting your PC browser with your phone for debugging](https://github.com/xarantolus/bromite-userscripts#creating-your-own-scripts).

I don't really see how I could help you here, except if you have a specific question for scripts in this repo
