### ISSUE TITLE
Cosmetic filter script lags Bromite after regaining focus

### ISSUE THREAD

**Issue by xarantolus** [xarantolus/bromite-userscripts#2]
Steps to reproduce:
1. Enable *only* the cosmetic filter script in Bromite settings
2. Visit any webpage where the script is injected
3. Switch to another app (or the launcher)
4. Switch back to Bromite
5. The page is now frozen and doesn't work anymore.
     * The URL bar and home page button of Bromite still work
     * Tapping any element on the page (e.g. text inputs) will lead to the page being unfrozen, but only after a significant (more than 10 seconds) delay

I currently don't exactly know why this happens, but it appears to only happen with the cosmetic filter script.

**Comment by simanchal-45** [comment]
Same for me.

**Comment by xarantolus** [comment]
This issue no longer reproduces in Bromite v101.0.4951.53 after https://github.com/bromite/bromite/pull/2037 was released (thank you Bromite devs ❤️)
