### ISSUE TITLE
new source for anti-adblock killer

### ISSUE THREAD

**Issue by MF-Debug** [xarantolus/bromite-userscripts#7]
Hi, can you please add [fuckfuckadblock](https://github.com/bogachenko/fuckfuckadblock) as a source for anti-adblock killer in your list? reek's anti-adblock list was outdated from a long time ago.

**Comment by xarantolus** [comment]
I added the new list, but depending on which sites you use it might not work perfectly, as the script only implements some basic blocking mechanisms

**Comment by MF-Debug** [comment]
Thanks, will keep that in mind.
